services: 
  reactjs-nginx-srv: 
    image: reactjs-nginx-jenkins:latest
    build:
      context: .
      dockerfile: dev.Dockerfile
    pull_policy: build
    container_name: reactjs-jenkin-cont
    ports: 
      - "3000:80"
